# Copyright (c) 2026 Terrene Foundation (Singapore CLG)
# Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0).
"""MosaicHub Content Moderation backend app factory (FastAPI).

Entry point for `scripts/run_backend.sh`. The scaffold is PRE-BUILT —
students do not edit this file.
"""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from typing import AsyncIterator

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

load_dotenv()

from .routes import build_router  # noqa: E402
from .startup import run_startup  # noqa: E402

log = logging.getLogger("metis.media.app")


@asynccontextmanager
async def _lifespan(app: FastAPI) -> AsyncIterator[None]:
    logging.basicConfig(
        level=os.environ.get("LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    log.info("metis.media.app.starting")
    await run_startup()
    log.info("metis.media.app.ready")
    try:
        yield
    finally:
        log.info("metis.media.app.stopping")


def create_app() -> FastAPI:
    app = FastAPI(
        title="MosaicHub Content Moderation — Metis Week 6",
        lifespan=_lifespan,
    )
    # CORS: localhost-only training scaffold on synthetic data. The wildcard
    # is acceptable HERE because the backend binds to 127.0.0.1 by default
    # (see config.py) and the dataset contains no real PII or real user
    # imagery. Do NOT copy this CORS configuration into a production service.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )
    app.include_router(build_router())
    return app


app = create_app()
