"""Metis Week 4 backend app factory (Nexus + kailash-ml).

Entry point for `scripts/run_backend.sh`. The scaffold is PRE-BUILT — students
do not edit this file; they commission the 501-stub route handlers via Claude
Code per PLAYBOOK.md phases 4, 10-12, 13.

Per canonical-values.md §7: binds to localhost:8000 (env override
KAILASH_NEXUS_PORT).
"""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from typing import AsyncIterator

from dotenv import load_dotenv
from fastapi import FastAPI

# Load .env BEFORE any os.environ access per rules/env-models.md.
load_dotenv()

from .routes import build_router  # noqa: E402
from .startup import run_startup  # noqa: E402

log = logging.getLogger("metis.app")


@asynccontextmanager
async def _lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Lifespan hook: run startup, then yield, then teardown."""
    logging.basicConfig(
        level=os.environ.get("LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    log.info("metis.app.starting", extra={"service": "nexus-backend"})
    await run_startup()
    log.info("metis.app.ready", extra={"service": "nexus-backend"})
    try:
        yield
    finally:
        log.info("metis.app.stopping", extra={"service": "nexus-backend"})


def create_app() -> FastAPI:
    """Build the Metis backend app.

    Wires routes, ml_context, and lifespan startup. Used by uvicorn and by
    `tests/integration/` Tier-2 tests via TestClient.
    """
    app = FastAPI(
        title="Metis Week 4 — Northwind Control Tower",
        version="2026-04-16",
        description=(
            "Student-commissioned Nexus backend. Endpoints return 501 with "
            "TODO-STUDENT banners until students prompt Claude Code to wire "
            "them per PLAYBOOK.md. See SCAFFOLD_MANIFEST.md."
        ),
        lifespan=_lifespan,
    )
    app.include_router(build_router())
    return app


# Module-level app instance for `uvicorn src.backend.app:app`.
app = create_app()


def main() -> None:
    """Run via `python -m src.backend.app` — used by scripts/run_backend.sh."""
    import uvicorn

    port = int(os.environ.get("KAILASH_NEXUS_PORT", "8000"))
    host = os.environ.get("KAILASH_NEXUS_HOST", "127.0.0.1")
    log.info("metis.app.bind", extra={"host": host, "port": port})
    uvicorn.run(
        "src.backend.app:app",
        host=host,
        port=port,
        reload=False,
        log_level=os.environ.get("LOG_LEVEL", "info").lower(),
    )


if __name__ == "__main__":
    main()
