# Copyright (c) 2026 Terrene Foundation (Singapore CLG)
# Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0).
"""Arcadia Retail backend app factory (FastAPI).

Entry point for `scripts/run_backend.sh`. The scaffold is PRE-BUILT —
students do not edit this file.
"""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from typing import AsyncIterator

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

load_dotenv()

from .routes import build_router  # noqa: E402
from .startup import run_startup  # noqa: E402

log = logging.getLogger("metis.app")


@asynccontextmanager
async def _lifespan(app: FastAPI) -> AsyncIterator[None]:
    logging.basicConfig(
        level=os.environ.get("LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    log.info("metis.app.starting")
    await run_startup()
    log.info("metis.app.ready")
    try:
        yield
    finally:
        log.info("metis.app.stopping")


def create_app() -> FastAPI:
    app = FastAPI(title="Arcadia Retail — Metis Week 5", lifespan=_lifespan)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )
    app.include_router(build_router())
    return app


app = create_app()
